### ISSUE TITLE
Not a actual, just a question :D

### ISSUE THREAD

**Issue by WarpWing** [felipendc/vicyos-build-folder#2]
Hello! I was just wondering how did you change the name of the OS like the picture below?
![](https://cdn.discordapp.com/attachments/734545389340065837/759524164641095730/Screen_Shot_2020-09-26_at_5.16.39_PM.png)

**Comment by felipendc** [comment]
Hi, here is the code where I make the change: 
https://github.com/felipendc/vicyos-build-folder/blob/master/Vicyos-Nord-Stable/local_build-vicyos-nord.sh#L64

and this is the source file:
https://github.com/felipendc/vicyoslinux-unified-iso/blob/master/archiso/airootfs/etc/vicyos-release
