### ISSUE TITLE
I feel silly.. but what is the user password to the live isos?

### ISSUE THREAD

**Issue by Adventure4Life** [felipendc/vicyos-build-folder#3]
Downloaded the live isos (nord, xfe and herbs) but they all ask for a user password when you boot inot them and I do not know what they are and cannot seem to find the info on this page or the sourceforge page?

**Comment by darylwalsh** [comment]
liveuser uname only, password field disappears, login

**Comment by felipendc** [comment]
Now, it doesn't need to enter a password.
